
before_all do
  ensure_git_branch
  git_pull
end

platform :android do
  
  desc 'Build the Android application.'
  private_lane :build do
    gradle(
      tasks:["clean", "assembleRelease", "bundleRelease"],
      flags: "-x lint -x lintVitalRelease --stacktrace",
      print_command: true,
      project_dir: '../android/'
    )
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
  end
  
end


