
before_all do
  ensure_git_branch
  git_pull
end

platform :android do
  
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: '../android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: '../android/')
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
  end
  
end


