
before_all do
  ensure_git_branch
  git_pull
end

platform :android do
  
  desc 'Build the Android application.'
  private_lane :build do
    gradle(
      tasks:["clean", "assembleRelease", "bundleRelease"],
      flags: "-x lint -x lintVitalRelease --stacktrace",
      print_command: true,
      project_dir: '../android/'
    )

    output_file = "/Users/vagrant/deploy/";

    APK_LOCATION = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    ABB_LOCATION = "#{lane_context[SharedValues::GRADLE_AAB_OUTPUT_PATH]}"
      
    sh("mv #{APK_LOCATION} #{output_file}")
    sh("mv #{ABB_LOCATION} #{output_file}")
    
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
  end
  
end


